site_name: OSG Networking Area
site_url: https://osg-htc/networking/
repo_url: https://github.com/osg-htc/networking/
theme: 
  name: material
  custom_dir: osgthedocs

extra_css:
  - css/extra.css

pages:
  - OSG Networking Area: 'index.md'
  - Network Monitoring (perfSONAR):
    - 'Motivation': 'perfsonar-in-osg.md'
    - 'Deployment': 'perfsonar/deployment-models.md'
    - 'Installation and Maintenance': 'perfsonar/installation.md'
    - 'Frequently Asked Questions': 'perfsonar/faq.md'
  - Network Troubleshooting: 
    - 'Network Troubleshooting': 'network-troubleshooting.md'
    - 'OSG Network Debugging Document': 'network-troubleshooting/osg-debugging-document.md'
  - Network Services: 
    - 'Infrastructure Monitoring': 'perfsonar/psetf.md'
    - 'Network Datastore and Streaming' : 'osg-network-services.md'
    - 'Network Analytics' : 'osg-network-analytics.md'

markdown_extensions:
  - admonition
  - codehilite

